title: Receptaculum
description: A basis for knowledge, experience and utilization
baseurl: ""
url: "https://receptaculum.github.io"

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "lib/", "bin/", "Rakefile", "example"]

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

toc:
  ordered_list: true

heading_anchors: true

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "상단부 보기"

footer_content: "<a href=\"https://github.com/just-the-docs/just-the-docs\">just-the-docs</a><br>&copy; 2017-2020 <a href=\"https://github.com/pmarsceill\">Patrick Marsceill</a> | <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license</a> 의거"

last_edit_timestamp: false
last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: dark

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
